version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  clientappui:
    build:
      context: .
      dockerfile: ClientAppUI/Dockerfile
    container_name: clientappui
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  identityservice:
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    container_name: identityservice
    ports:
      - "8050:8050"
      - "8051:8051"
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=master;Password=mypassword;Database=accountsdb"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vessel@web.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
