version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  clientappui:
    build:
      context: .
      dockerfile: ClientAppUI/Dockerfile
    container_name: clientappui
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "SecurePassword123"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/https:ro
    depends_on:
      - rabbitmq
    networks:
      - app-network

  identityservice:
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    container_name: identityservice
    ports:
      - "8050:8050"
      - "8051:8051"
    depends_on:
      - rabbitmq
      - accountdb
    networks:
      - app-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  storefrontservice:
    build:
      context: .
      dockerfile: StorefrontService/Dockerfile
    container_name: storefrontservice
    ports:
      - "8060:8060"
      - "8061:8061"
    depends_on:
      - rabbitmq
      - assortmentdb
    networks:
      - app-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  accountdb:
    image: postgres:15
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: accountdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_accountdb:/var/lib/postgresql/data 
    networks:
      - app-network

  assortmentdb:
    image: postgres:15
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: assortmentdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata_assortmentdb:/var/lib/postgresql/data 
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin 
    environment:
      PGADMIN_DEFAULT_EMAIL: vessel@web.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - accountdb
      - assortmentdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_accountdb:
  pgdata_assortmentdb:  
