// <auto-generated />
using DatabasesAccess.AssortmentDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabasesAccess.AssortmentDb.Migrations
{
    [DbContext(typeof(AssortmentContext))]
    partial class AssortmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Imagelink")
                        .HasColumnType("text")
                        .HasColumnName("image_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("product");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.ProductConfiguration", b =>
                {
                    b.Property<long>("ProductItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<long>("VariationOptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("option_id");

                    b.HasKey("ProductItemId", "VariationOptionId");

                    b.HasIndex("VariationOptionId");

                    b.ToTable("product_configuration");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.ProductItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer")
                        .HasColumnName("cooking_time");

                    b.Property<string>("Imagelink")
                        .HasColumnType("text")
                        .HasColumnName("image_link");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_item");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Variation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("variation");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.VariationOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<long>("VariationId")
                        .HasColumnType("bigint")
                        .HasColumnName("variation_id");

                    b.HasKey("Id");

                    b.HasIndex("VariationId");

                    b.ToTable("variation_option");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Product", b =>
                {
                    b.HasOne("DatabaseModels.AssortmentDatabaseModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.ProductConfiguration", b =>
                {
                    b.HasOne("DatabaseModels.AssortmentDatabaseModels.ProductItem", "ProductItem")
                        .WithMany("Configurations")
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_configuration_product_item_id");

                    b.HasOne("DatabaseModels.AssortmentDatabaseModels.VariationOption", "VariationOption")
                        .WithMany("Configurations")
                        .HasForeignKey("VariationOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_configuration_variation_option_id");

                    b.Navigation("ProductItem");

                    b.Navigation("VariationOption");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.ProductItem", b =>
                {
                    b.HasOne("DatabaseModels.AssortmentDatabaseModels.Product", "Product")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_item_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Variation", b =>
                {
                    b.HasOne("DatabaseModels.AssortmentDatabaseModels.Category", "Category")
                        .WithMany("Variations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_variation_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.VariationOption", b =>
                {
                    b.HasOne("DatabaseModels.AssortmentDatabaseModels.Variation", "Variation")
                        .WithMany("VariationOptions")
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_variation_option_variation_id");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Product", b =>
                {
                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.ProductItem", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.Variation", b =>
                {
                    b.Navigation("VariationOptions");
                });

            modelBuilder.Entity("DatabaseModels.AssortmentDatabaseModels.VariationOption", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
